title: Testing personal website
email: david@example.com
description: "Blog personal en pruebas - github pages + jekyll"
baseurl: "" # solo si usas user.github.io
url: "https://dalva77.github.io"
theme: minima