remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Testing personal website
description: Blog personal en pruebas - github pages + jekyll
author:
  name: "David Alvarez"

